Vagrant.configure("2") do |config|
 
  config.vm.provision "docker"
 
  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
 
  config.vm.define "dockerhost"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9300, host: 9300
  config.vm.network "forwarded_port", guest: 5601, host: 5601
    
  config.vm.synced_folder "c:/src/flexlm-license-elk", "/src"
 
  config.vm.provider :virtualbox do |vb|
    vb.name = "dockerhost"
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
 
end